# Generated by Django 6.1 on 2026-09-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
