# Generated by Django 6.1 on 2026-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_suggestion_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Kallavan', max_length=100, verbose_name='Autor'),
        ),
    ]
